#!/bin/bash
#
# postBuild runs with cwd at the project root
#
# install jupyter_shoebot extension
#
apt-get install gir1.2-gtk-3.0 gir1.2-rsvg-2.0 gobject-introspection libgirepository1.0-dev libglib2.0-dev libpango1.0-dev python-gi-cairo python-gobject
pip install .
jupyter kernelspec install shoebot_kernel --sys-prefix
